### ISSUE TITLE
Moving pipeline to a new file results in duplicate pipeline error

### ISSUE THREAD

**Issue by kmugrage** [tomzo/gocd-yaml-config-plugin#1]
https://github.com/kmugrage/yaml-gocd-test

I had 3 pipelines in one file and it worked great. I then moved 2 of them to a new file so they could be managed separately. This resulted in GoCD throwing an error saying I have a duplicate pipeline name.

<img width="754" alt="screen shot 2016-07-21 at 12 11 23 pm" src="https://cloud.githubusercontent.com/assets/3209933/17031949/506aef46-4f3c-11e6-9681-78503e119704.png">

**Comment by tomzo** [comment]
In your last commit https://github.com/kmugrage/yaml-gocd-test/commit/9b36ee4f4f38e4928bccd6c3e89994373e019549 you really do have 2 pipelines named `FunctionalTesting` in both files. Is it that simple problem or I am missing something?

**Comment by kmugrage** [comment]
Oh geez do I feel stupid! I committed the change and didn't push. Wow.

Sorry :)
