### ISSUE TITLE
yaml plugin does not parse null

### ISSUE THREAD

**Issue by birchb1024** [tomzo/gocd-yaml-config-plugin#107]
With code like this:

`secure_variables: null`

we get the  dreaded `java.lang.String cannot be cast to java.util.Map` error.

I don't think the YamlBeans parser can cope with it - even though it's valid YAML... This is annoying because my pipelines are generated by PyYaml which inserts null when there is no object. 

PLugin Version 0.6.0

**Comment by birchb1024** [comment]
Similar issue with: `working_directory: null` except this time GoCD it tries to change to the directory `null`.

**Comment by tomzo** [comment]
I believe this was fixed a while ago. If not please reopen
