### ISSUE TITLE
Use dir without dir being a git-repository

### ISSUE THREAD

**Issue by ChristianKniep** [tomzo/gocd-yaml-config-plugin#111]
I am deploying GoCD as container stack and I was hoping to just put two files (`environment.gocd.yaml` and `pipeline.gocd.yaml`) in the gocd-server to bootstrap the pipelines from.
So far I get the error, that gocd is looking for a git repository, which my two files are not.

Can I just use a plain directory instead?
```
<config-repos>
     <config-repo pluginId="yaml.config.plugin" id="gocd-config-repo">
       <git url="file:///opt/qnib/gocd/repo/" />
     </config-repo>
   </config-repos>
```
compose-file:
```
- source: gocd_repo_pipelines
        target: /opt/qnib/gocd/repo/pipelines.gocd.yaml
        uid: '0'
        gid: '0'
        mode: 0444
      - source: gocd_repo_environments
        target: /opt/qnib/gocd/repo/environments.gocd.yaml
        uid: '0'
        gid: '0'
        mode: 0444
```

**Comment by tomzo** [comment]
> Can I just use a plain directory instead?

No. That has to be what GoCD considers an SCM material.

You could mount `/opt/qnib/gocd/repo` in docker and make it a git repository with `git init` and `git add *`
