### ISSUE TITLE
artifactCleanupProhibited support

### ISSUE THREAD

**Issue by remy-tiitre** [tomzo/gocd-yaml-config-plugin#121]
Maybe the support is already there but I could not find it from documentation. In GoCD xml configuration its called artifactCleanupProhibited.

**Comment by tomzo** [comment]
Hi @remy-tiitre 

It's part of [stage config](https://github.com/tomzo/gocd-yaml-config-plugin#stage):
```
keep_artifacts: yes
```

But you are right, it is a bit hard to find. I'll improve the docs around this.

**Comment by remy-tiitre** [comment]
Ok, thank you. I did notice that but was not 100% sure. This issue can be marked as solved then.
