### ISSUE TITLE
Broken after update to 20.2

### ISSUE THREAD

**Issue by wilful** [tomzo/gocd-yaml-config-plugin#138]
Hi! After upgrade server to 20.2 version. i can't add new Yaml configs.

`Not allowed to refer pipeline group 'test' from the config repository.;; `

If i remove 'groups' then

```
.gocd.yaml; Pipeline hiera;
1. Missing field 'group'.
```

**Comment by tomzo** [comment]
Hi @wilful 

Please have a look at [release notes in 20.2 version](https://www.gocd.org/releases/#20-2-0)

There is a new feature which allows to specify policies around config-repos - https://docs.gocd.org/20.2.0/advanced_usage/pipelines_as_code.html#specifying-rules 

You'll have to define which pipelines are allowed to be declared in which config repos.

**Comment by wilful** [comment]
Thanks for help!
