### ISSUE TITLE
Pipeline Export always returns `format_version` = 3

### ISSUE THREAD

**Issue by maheshp** [tomzo/gocd-yaml-config-plugin#140]
The pipeline export converts the plugin to YAML. The `format_version` is always set to 3 while the [latest version](https://github.com/tomzo/gocd-yaml-config-plugin#Format-version) supported by the plugin is 9.

The `format_version` returned is hard coded to 3 - https://github.com/tomzo/gocd-yaml-config-plugin/blob/master/src/main/java/cd/go/plugin/config/yaml/transforms/RootTransform.java#L33
This needs to change to the appropriate version supported by the plugin.

**Comment by tomzo** [comment]
fixed in 0.13.0
