### ISSUE TITLE
Support scm ref for config repo configuration

### ISSUE THREAD

**Issue by sahlone** [tomzo/gocd-yaml-config-plugin#150]
Need to support the scm ref for the plugin config itself. I am not talking about plugable scm for the pipeline.
Want to do something like this
```
<scms>
<scm id="7e0072f2-dd30-4cdc-b618-336be0e5e14d" name="Portal-pull-request">
<pluginConfiguration id="xxx" version="1" />
<configuration>
<property>
<key>url</key>
<value>mygit_repo</value>
</property>
<property>
<key>username</key>
<value>blablabla</value>
</property>
<property>
<key>password</key>
<encryptedValue>gjhgjhghgjhgjhghjgj</encryptedValue>
</property>
</configuration>
</scm>
</scms>
```

In server config `cruise-config.yaml`
```
<config-repo pluginId="yaml.config.plugin" id="QA-Merchant-Simulator">
      <scm ref="7e0072f2-dd30-4cdc-b618-336be0e5e14d" />
</config-repo>
```
This will help me deduplication of the same git repo configs at two places, one in scm and another in config. repo.

**Comment by chadlwilson** [comment]
At the moment this is not able to be supported by plugins or the GoCD server, so closing this as stale. Probably needs to be discussed on the main repo, although possibly not enough contributors to implement even if desirable.
