### ISSUE TITLE
Error exporting pipeline created using the UI.

### ISSUE THREAD

**Issue by Pakoke** [tomzo/gocd-yaml-config-plugin#155]
For some reason GoCD and gocd-yaml-config-plugin is not exporting some pipelines created through the wizard of GoCD.
We created some pipelines using the UI and for some reason we have the next error everytime that we try to export it.

``There was an unknown error downloading the pipeline configuration. Please refresh the page and try again.``

![image](https://user-images.githubusercontent.com/15789394/146971869-46670e50-c996-4ab6-a482-a8f72540d891.png)

We tried to delete multiples steps to find out what it was causing but at the end we didn't found anything. We did this because we are using multiples steps as a custom commands and we blame to GoCD UI to write some characteres not supported by the plugin.

GOCD Version: 21.2.0
Server running on CentOS host

**Comment by chadlwilson** [comment]
Are you able to check what is in the GoCd server logs corresponding with this error?

Also would be interesting to understand what you find is not supported by the plugin that you need the UI for.

**Comment by sweetfxv** [comment]
Hello @Pakoke.
Related to this problem, is your pipeline fetching artifact from the same pipeline on any stage?
If there are **Fetch Artifact Task**, the parameter **Pipeline Name** must be set, can't be empty.
![image](https://user-images.githubusercontent.com/6692137/148654386-1c0d143d-d66c-4991-acfe-37cf6a4b8231.png)
![image](https://user-images.githubusercontent.com/6692137/148654401-60d449cb-ea93-4804-af14-db69cf2b8dfe.png)

### Possible solutions
1. **Always** set the pipeline name on Fetch Artifact Task.
2. Modify plugin to detect when the property **Pipeline Name** is **null** and replace by the main name. 

### Trace error
You can trace this error using browser developers tools.

1. Open web browser dev tools
2. Export Pipeline to YAML/JSON 
![image](https://user-images.githubusercontent.com/6692137/148654621-2be75f48-00a7-4931-94af-356f766904dc.png)
3. Now, in the console should be a message like this
![image](https://user-images.githubusercontent.com/6692137/148654668-849511b1-7ef9-41aa-9d88-a5c56da94591.png)
4. Click on it. On the **Network** tab a row will be highlighted, click it and choose **Preview** tab
![image](https://user-images.githubusercontent.com/6692137/148654827-1a2d3a56-f9cd-416f-83e7-b862f5458b10.png)
![image](https://user-images.githubusercontent.com/6692137/148654933-707f31cc-5692-45c6-91b6-ea9d10ac43db.png)




I hope this helps you.

**Comment by vernonr3** [comment]
I'm experience the same problem when clicking on either the JSON or YAML Configuration plugin. 

Having chased the error through the browser dev tools I've discovered the following:

- A 422 unprocessable entity is being returned from http://<ipaddr>:8153/go/api/admin/export/pipelines/KMCloudMonitorServer?plugin_id=yaml.config.plugin
- the response message is : message | 'Cannot  invoke "com.thoughtworks.go.config.CaseInsensitiveString.toString()"  because the return value of  "com.thoughtworks.go.config.FetchTask.getPipelineName()" is null'

So the dialog knows the name of the pipeline - but this isn't (it would appear) being fed to the event..





</span>

**Comment by chadlwilson** [comment]
@vernonr3 Which GoCD Server version is this? And can you find the corresponding full stack trace in the server logs?
