### ISSUE TITLE
Multibranch pipeline example request

### ISSUE THREAD

**Issue by panjacek** [tomzo/gocd-yaml-config-plugin#156]
Is it possible to have multibranch pipelines with some steps executed only on certain branches only?
I can't find any example about it.

or branch must be hardcoded per pipeline ??

I am looking to have a single pipeline definition to build and test on master and any active pull request branches.

**Comment by Zer0S2m** [comment]
Good afternoon

Maybe the following documentation blocks will help you:
1. [GoCD Fan-in Dependency Management](https://docs.gocd.org/current/advanced_usage/fan_in.html)
2. [Pipelines as code - examples](https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html#examples)
