### ISSUE TITLE
nant_path label does not work

### ISSUE THREAD

**Issue by ccaravaca** [tomzo/gocd-yaml-config-plugin#175]
My task for nant:
- nant:
    run_if: passed
    working_directory: "."
    build_file: Installer\default.build
    target: clean
    nant_path: C:\Desarrollo\nant\nant-0.92\bin\nant.exe
**In GoCD, the nant_path field is empty**. I have tried in GoCD v 22.2.0-14697 and  v 22.3.0-15301

**Comment by chadlwilson** [comment]
The `nant_path` shouldn't have the actual `exe` in it - it should be a folder, i.e `C:\Desarrollo\nant\nant-0.92\bin` - the same as the description in GoCD.

![image](https://user-images.githubusercontent.com/29788154/223119442-b0b05362-e5dc-474b-8c21-6cb4a8a85d06.png)

Other than that, please share exactly what you actually see in GoCD to make it easier to help you.

**Comment by ccaravaca** [comment]
I would like the next task in GoCD:
![Captura de pantalla 2023-03-06 150002](https://user-images.githubusercontent.com/119498082/223131161-af158eed-46c4-4978-a858-4a612b1a74e5.png)
This is my yaml task:
            - nant:
                nant_path: C:\Desarrollo\nant\nant-0.92\bin
                build_file: Installer\default.build
                target: clean
                run_if: passed
And this is the configuration that I obtain using the plugin in GoCD:
![Captura de pantalla 2023-03-06 150145](https://user-images.githubusercontent.com/119498082/223131514-6a5a19b3-2854-4dd2-9d13-75676a3b07f2.png)

As you can see, the NAnt Path field is empty.
