### ISSUE TITLE
Forcing updates, determining when last update was performed

### ISSUE THREAD

**Issue by blalor** [tomzo/gocd-yaml-config-plugin#20]
Is there a way to force the plugin to update the config on demand?  It doesn't appear that https://api.gocd.io/current/#notify-git-materials is applicable, as the repositories aren't listed in the list of available materials.

Along those lines, it would be nice if the plugin indicated when it had last performed an update.

**Comment by tomzo** [comment]
It is possible to send POST for materials which are used in config repositories. I added that support in GoCD https://github.com/gocd/gocd/pull/2193 few months ago and I use it on nearly all repos.

**Comment by blalor** [comment]
Ah, interesting.  I tried that, but didn't see anything in the logs indicating that it'd had an affect.  I'll poke at that some more.

**Comment by tomzo** [comment]
I have hooks on gitlab which trigger GoCD, URL for hook looks like this:
```
http://<user>:<password>k@<gocd-host>/go/api/material/notify/git/?repository_url=<url-git>
```
And `<url-git>`  is the same string which you put in `config-repo` section:
```
<config-repo plugin="yaml.config.plugin">
      <git url="<url-git>" />
    </config-repo>
```
I do not recall if this was supposed to generate some log message, it might have been on DEBUG level.
