### ISSUE TITLE
Error messages about parsing does not contain any clues in the log

### ISSUE THREAD

**Issue by cblomqvist** [tomzo/gocd-yaml-config-plugin#23]
Here is a sample from the log:
`GoRepoConfigDataSource:158 - Failed to parse configuration material https://github.com/cblomqvist/gocd-pipelines-yaml.git by Plugin yaml.config.plugin`

Here is the error message I can see in the GoCD GUI when clicking the Error notification in the bottom right corner:
`ci.gocd.yaml; - Failed to parse pipeline pac1_privatpension; java.util.ArrayList cannot be cast to java.util.Map`

It is slightly better but more clues of where that error happens would be nice.

**Comment by tomzo** [comment]
fixed by https://github.com/gocd/gocd/issues/3463
