### ISSUE TITLE
Setup on GoCD version 17.x

### ISSUE THREAD

**Issue by mariowise** [tomzo/gocd-yaml-config-plugin#25]
I'm working with GoCD version 17.x and download the `.jar` as the setup says but I got this error

![image](https://cloud.githubusercontent.com/assets/1569327/26360448/19e8c5f0-3fa6-11e7-8f71-ea424f2648c3.png)

Any ideas?

**Comment by tomzo** [comment]
I am using this plugin with 17.4, there shouldn't be any problems. Please check your jar file.

**Comment by mariowise** [comment]
Yeah! my jar file was wrong. Thanks! @tomzo
