### ISSUE TITLE
Agents not visible in UI when added from configuration

### ISSUE THREAD

**Issue by Antauri** [tomzo/gocd-yaml-config-plugin#29]
Realistically speaking I don't know if this is an UI or configuration issue. We've integrated today GO.cd + this beautiful plugin (congrats) and we've also assigned agents to a specific environment (using their UUID). There's however an issue:

- the agents are assigned to the environment;
- but they don't show-up in the UI;
- no matter how many page refreshes we do, the same thing happens;
- to note, we're using the latest GO.cd (17+);

**Comment by tomzo** [comment]
Hi @Antauri 
I can't help you without more information. Can you post logs from server and the environment declaration which you used?
Also please note that it is not typical to add agents via yaml. It depends on your setup, but usually that is not be what you want. Agents can register with server and their id is stored in xml then.

**Comment by tomzo** [comment]
Closing due to lack of details.
