### ISSUE TITLE
Moving pipelines to another environment, does not update UI

### ISSUE THREAD

**Issue by Antauri** [tomzo/gocd-yaml-config-plugin#34]
Hello,

We had pipelines in two environments, then moved some of them into a new Environment. While the code (YAML) declares the proper grouping, the new environments exist on the "Environments" page but the main page UI still groups the pipelines in the old environment, while the Environments page shows them in their proper environment.

Any idea why there's a lag on the first dashboard page or what needs to reset?

**Comment by tomzo** [comment]
Hi, looks like a bug on server side. 
I preseument there are no health errors and you can indeed see the new association on both pages.
Can you report with more details on https://github.com/gocd/gocd/issues

Especially gocd version and snippets of the configs that you used (both yaml and xml).

**Comment by Antauri** [comment]
Found the issue. The "environments" variable was not in sync with each "group" on each pipeline. We keep the "Envrironments" in a separate file (it makes managing secure variables easier). If they're not in sync, the pipelines are going to be displayed on the "group" on the pipeline page and in their "environment" on the environments page.

IMHO, they are kind of redundant (unless there's a reason to have both). One should have priority or should actually implement the grouping logic.

Isn't the group the environment name? Or am I understanding wrong? If they are, there's a bit of redundancy (since I'm declaring the environments above the pipeliens and associating pipelines to envs, declaring group again seems redundant).

Don't think it's an UI issue. Maybe a consequence of the "pipeliens" on the environment listing, along with the "group" declaration.

**Comment by tomzo** [comment]
> Isn't the group the environment name? Or am I understanding wrong? 

Sorry, you got it all wrong. If you are new to GoCD. Please read GoCD user [manual first](https://docs.gocd.org/current/). Try some experiments with configuring through UI first to get to know the basic concepts, then move to using SCMs.
