### ISSUE TITLE
Support both .yaml and .yml file extensions by default

### ISSUE THREAD

**Issue by richardzone** [tomzo/gocd-yaml-config-plugin#35]
Hi awesome authors,

```
DEFAULT_FILE_PATTERN = "**/*.gocd.yaml"
```
Most of YAML tools (e.g. Ansible) supports both .yaml and .yml extensions. Could we also add .gocd.yml to the DEFAULT_FILE_PATTERN ?

Thanks,
Richard

**Comment by tomzo** [comment]
I agree that it would be nice to support `gocd.yml` too by default.
However, do you know what ant pattern would match both `gocd.yaml` and `gocd.yml` ? 
There is no OR in ant, (that I know of).

**Comment by arvindsv** [comment]
I was thinking we should change [this](https://github.com/tomzo/gocd-yaml-config-plugin/blob/0684ba4658ec76aa8484067916eb774fd3de22af/src/main/java/cd/go/plugin/config/yaml/AntDirectoryScanner.java#L13) to `pattern.split(",")`.

**Comment by gregorskii** [comment]
+1 :)

**Comment by tomzo** [comment]
Added in 0.6.0
