### ISSUE TITLE
Change "plugin" to "pluginId"

### ISSUE THREAD

**Issue by GaneshSPatil** [tomzo/gocd-yaml-config-plugin#37]
#### Type:
* Bug Report

#### Description
config-repo tag under config-xml has changed to contain "pluginId" attribute instead of "plugin"

#### Current Result
```
<config-repos>
   <config-repo plugin="json.config.plugin">
     <git url="https://github.com/tomzo/gocd-json-config-example.git" />
   </config-repo>
</config-repos>

```

#### Expected Result
```
<config-repos>
   <config-repo pluginId="json.config.plugin" id="repo1">
     <git url="https://github.com/tomzo/gocd-json-config-example.git" />
   </config-repo>
</config-repos>
```

More information
* https://github.com/gocd/gocd/issues/3671
* https://github.com/gocd/gocd/issues/3648

**Comment by ketan** [comment]
Close this issue?
