### ISSUE TITLE
How do I configure the plugin to pull from a private repository.

### ISSUE THREAD

**Issue by rltvty** [tomzo/gocd-yaml-config-plugin#40]
I have this in my config.xml

```
<config-repos>
    <config-repo pluginId="yaml.config.plugin" id="gocd-pipelines">
      <git url="git@github.com:MySite/gocd-pipelines.git" />
    </config-repo>
  </config-repos>
```

But `git@github.com:MySite/gocd-pipelines.git` is a private repo.  How do I specify auth for the plugin to be able to poll this repository?

Thanks

**Comment by tomzo** [comment]
Above configuration is correct. But GoCD does not support ssh auth yet. There are workarounds, you can configure ssh key for `go` user on your server host. see https://github.com/gocd/gocd/issues/951
This has really nothing to do this yaml plugin or config repo feature, so I am going to close it.

**Comment by rltvty** [comment]
thanks!

**Comment by Hkyx** [comment]
Hi @rltvty, I got the same issue, what had you did to solve that ?
Ty,

hkyx

**Comment by rltvty** [comment]
@Hkyx the link that tomzo posted should work, but we chose not to go that route.  we are going to start using another CI/CD solution instead.

**Comment by Hkyx** [comment]
Ok, thank you :) 

Yep, but seems not easy for me for the link :) I'll check that more :)
