### ISSUE TITLE
Empty secure variable cause execution fail

### ISSUE THREAD

**Issue by DavidUser** [tomzo/gocd-yaml-config-plugin#48]
If someone define a secure variable empty like:
```yaml
secure_variables:
  "GUEST_PASSWORD": ""
```
The future executions fail:
![gocd-plugin-secure-variable-failure](https://user-images.githubusercontent.com/6628028/32248223-1eb498ee-be6c-11e7-9b43-6746919db320.png)

**Comment by tomzo** [comment]
An empty secure variable is not a correct encrypted value. There is no such string that results in being encrypted to `""` so this is expected to be invalid.

**Comment by DavidUser** [comment]
@tomzo I agree that's not a valid value but the following commands fail isn't a correct failure response.
A acceptable error is the stop on the running command and maybe tell that has a secure variable with a empty value.
