### ISSUE TITLE
Encrypting values

### ISSUE THREAD

**Issue by ihr** [tomzo/gocd-yaml-config-plugin#5]
Hi,

Thanks for the great work. I'm trying out the configuration feature and I can't find correct way of encrypting the values to be put in the yml file. I couldn't find much in the docs, could you please provide some more information?

**Comment by tomzo** [comment]
Hi,

There isn't a convenient way to do this, yet. There should be UI or API at least in server to encrypt some text and save it in your configuration in SCM. There is an issue about this in gocd https://github.com/gocd/gocd/issues/1829

I tested that it is possible to take some text from cruise-config.xml and actually put it in yaml like this:
```yaml
secure_variables:
  MY_PASSWORD: "<encrypted-text>"
```

**Comment by ihr** [comment]
Hi,

Thanks, I will try that. I have first feedback of using the YAML configuration. Is there a forum or other place where we can discuss this? I think there could be some improvements in the documentation and I would like to make some suggestions

**Comment by tomzo** [comment]
There isn't a forum yet. You're very welcome to open an issue with suggestions or PR with documentation improvements.

**Comment by ihr** [comment]
Thank you, I created a pull requests regarding the README. Once I tested a way to have the password secured I will submit another PR

**Comment by jskswamy** [comment]
For now this can be achieved  using `openssl`, refer this [pull request](https://github.com/tomzo/gocd-yaml-config-plugin/pull/16/commits/9576631470188e75068233e459b3f0ddd5ef65d6)

**Comment by ketan** [comment]
@tomzo — can you close this, since the encryption API is available. https://api.gocd.org/current/#encrypt-a-plain-text-value since 17.1. I'll update the README in another PR.
