### ISSUE TITLE
Is it possible to define template in yaml format?

### ISSUE THREAD

**Issue by olegmayko** [tomzo/gocd-yaml-config-plugin#51]
Hi, maybe i overlooked  it in the documentation, but how can i specify the pipeline as template , so i can set the reference as in one of the examples. 
and related question: how can i specify reference to the parameter in the pipeline, 
eg. 
  mypipe1: # definition of mypipe1 pipeline
  ...
    parameters: # list of parameters that can be configured for a pipeline
      param1: value1
  jobs:
  test: 
environment_variables:
  param1: #{param1}

it does not work. :(. 
thank you

**Comment by tomzo** [comment]
It is not possible to define template in yaml yet.
You can only refer to a template configured in XML (via UI or API). That is available from plugin version 0.6.0 and [GoCD 17.11](https://www.gocd.org/releases/)

**Comment by olegmayko** [comment]
@tomzo  thanks, can you help me with understanding how can i make propagate parameters to env variables using yaml plugin? thank you in advance

**Comment by tomzo** [comment]
@olegmayko  please see #52 which addresses similar use case that you need
