### ISSUE TITLE
Point the config to different branch of git repository

### ISSUE THREAD

**Issue by vaibhavparnalia** [tomzo/gocd-yaml-config-plugin#58]
`<config-repo pluginId="yaml.config.plugin" id="repo1">
      <git url="ssh://git@bitbucket.samplerepo.com/sampleproject/gocd-server-yaml.git" />
    </config-repo>`

Hello, is it possible to point the config to a different branch of the git repository?
Something like 

`<git url="ssh://git@bitbucket.samplerepo.com/sampleproject/gocd-server-yaml.git" git branch="develop" />`

**Comment by arvindsv** [comment]
The attribute is `branch`. Same as a normal git material in GoCD. It was mentioned in the [chat room](https://gitter.im/gocd/configrepo-plugins?at=58bfe8e4de504908225f74ba) sometime, as well.

**Comment by vaibhavparnalia** [comment]
Thanks @arvindsv for pointing to the chat room as well!
