### ISSUE TITLE
Create yaml pipeline as initially paused

### ISSUE THREAD

**Issue by tpidor** [tomzo/gocd-yaml-config-plugin#64]
1. When creating pipeline from GoCD GUI, the initial state of the pipeline is paused.
2. When creating the pipeline directly into config xml in GoCD GUI config xml field, the initial state of the pipeline is active.
3. When creating the pipeline as yaml and then pushed into git config-repo, the initial state is also active. Is there some attribute that can make the pipeline initial state as paused?

**Comment by tomzo** [comment]
Someone already mentioned this on the chat. We concluded that most users do not want to the new pipelines defined in source control to be paused. It is possible to implement though. But this is not specific to yaml plugin. You can open an issue on https://github.com/gocd/gocd/issues or better yet provide a PR there.

**Comment by MRajasekhar** [comment]
Hi,
I ran into same issue today, we don't have any option to create pipelines in pause state from yaml config. Is it only available in API call as header ? 

if there is an option, please let me know . 

thank you in advance. 

Regards,
Rajasekhar
