### ISSUE TITLE
Pipeline configurations can't be seen in the GoCD UI

### ISSUE THREAD

**Issue by cristim** [tomzo/gocd-yaml-config-plugin#66]
Sometimes it's really useful to see the pipeline configuration in the UI, even if it can't be edited, in order to verify if the configuration looks as it should, as well as for debugging purposes.

**Comment by tomzo** [comment]
For debugging purposes the best for now is querying the API to see what configuration is actually used by the server.
This mentioned a few times so far that perhaps a dedicated UI for config-repos would be probably best. However that needs to happen in the core, it is not specific to yaml plugin. 
You can open such request on https://github.com/gocd/gocd/issues

**Comment by manojtr** [comment]
Hi @tomzo 

I tried this API curl -v 'https://go.go.xx/go/api/admin/pipelines/test' -u 'user:pass' -H 'Accept: application/vnd.go.cd.v3+json' and it returns 404. gocd version 16.12.

**Comment by tomzo** [comment]
Hi @manojtr 
With gocd version 16.12, It's hard to say what might be wrong there. Those were early days of config-repos and possibly pipelines as code might have been excluded in the API. I'd suggest you upgrade to a more recent version. Many improvements and fixes were made since then.
