### ISSUE TITLE
"lock_behavior: unlockWhenFinished" seems not working

### ISSUE THREAD

**Issue by tpidor** [tomzo/gocd-yaml-config-plugin#68]
Here's the snippet of my pipeline:
```
    label_template: ${App_Build}
    lock_behavior: unlockWhenFinished
    materials: *Materials
```
GoCD Server Version = 16.8.0 (3929-4d871a65f9a14b157006236d8fda3460bcafcadb)
YAML Plugin Version = 0.6.0
However, the pipeline doesn't seem to lock while it is running. Is there something I missed? I tried lockOnFailure, same result. Please see snapshot below.
![unlockwhenfinished_notworking](https://user-images.githubusercontent.com/36467516/36881205-fa62b45c-1e20-11e8-8adb-1a57b93f6b82.JPG)

**Comment by arvindsv** [comment]
`unlockWhenFinished` was introduced in 17.12. See [this](https://github.com/tomzo/gocd-yaml-config-plugin#pipeline-locking). In 16.8, which is quite old, there's only a boolean called `locking` and it will not unlock when finished. If the pipeline fails, it'll keep it locked.

**Comment by tpidor** [comment]
@arvindsv Added the snippet below, it works perfectly now. Thanks heaps!
```
    locking: on # for GoCD < 17.12
```
