### ISSUE TITLE
YAML Pipeline with secure_variables cannot easily be ported to a non-Prod GoCD server

### ISSUE THREAD

**Issue by tpidor** [tomzo/gocd-yaml-config-plugin#69]
We have Prod and non-Prod GoCD server. All pipelines are still defined as config xml. In non-Prod, we just copy/paste the pipeline xml we need for dev purposes. To easily configure pipelines to another server, we're aiming to convert xml into yaml pipelines. This is currently in progress and seeing great features with yaml pipeline config. However, one of the challenges just like xml, yaml pipelines with encrypted variables cannot easily be configured to another server. I read some article, to solve this particular challenge is to make sure GoCD server cipher key between Prod and non-Prod are the same. However, it is advised to keep these cipher key file to be different in every GoCD server for security reasons.

Does my explanation makes sense? Is there some better way of managing encrypted values in Pipeline As Code?

**Comment by tomzo** [comment]
Hi @tpidor 

> Is there some better way of managing encrypted values in Pipeline As Code?

There is only one way to manage secrets in yaml - with text encrypted by gocd cipher. There were some discussions on making GoCD secret backends more extensible, but that work needs to happen in the core.
IMHO your Prod and non-Prod split is just wrong, or at least will be when you move to yaml. A GoCD server per team or project makes some sense, but split between prod and non-prod seems invalid to me. I would merge those servers into one.

> However, it is advised to keep these cipher key file to be different in every GoCD server for security reasons

From your description it doesn't seem that you have split the servers for security reasons and you actually want to have the same secrets in both servers. So I think it would be OK to have to same cipher in both servers.

**Comment by tpidor** [comment]
Hi @tomzo 

Our non-prod GoCD is for development and experimentations. We can trial some plugins or some new config in non-Prod before implementing to Prod GoCD. This also means we could easily use the same pipeline config used in Prod into non-prod GoCD or vice versa. In this particular issue, I'm developing/writing the yaml pipeline with secure variables and used in non-Prod GoCD. However when I moved it to Prod, it failed because the secure variable is not compatible in Prod.

In this case, there's no other way of managing secured variables in yaml config so that the pipeline config can easily be migrated from one GoCD server to another?

**Comment by tomzo** [comment]
> there's no other way of managing secured variables in yaml config so that the pipeline config can easily be migrated from one GoCD server to another?

No, there is no other way. The only solution at the moment would be to have same cipher in both servers.

**Comment by tpidor** [comment]
Thanks
