### ISSUE TITLE
clean_workspace = true does nothing

### ISSUE THREAD

**Issue by remy-tiitre** [tomzo/gocd-yaml-config-plugin#71]
I added it to my stage config but it seems to be ignored. When I checked Pipeline config xml after this change there was no cleanWorkingDir attribute on the stage and offcourse the stage was not cleaned either. GoCD version 18.2.0 with format_version: 2 pipeline config. I haven't used this feature before, so not sure if it works on other versions.

**Comment by tomzo** [comment]
Hi,

> When I checked Pipeline config xml after this change there was no cleanWorkingDir attribute on the stage and offcourse the stage was not cleaned either.

It looks as if you expected the yaml configuration to affect your xml config. But it does not work like that. You either store pipelines in a config repo OR you keep it in xml and edit via UI/API. 

>  I haven't used this feature before, so not sure if it works on other versions.

Here is an introduction document -
 https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html

I need more details from you to verify if this is a bug or misuse.
Please post
 * What did you configure in xml in `<config-repos>` section.
 * The contents of your configuration repository with complete yaml. At least of the pipeline which you are reporting about.
 * Are there any errors in server health status window?

**Comment by remy-tiitre** [comment]
You understood me incorrectly. I checked that xml config from the pipeline. Where it shows what config was used for that run. And under that you can actually see how the yaml was interpreted and what settinds ended up into config (you will see full, merged xml there). If I'm not mislead. So the yaml is parsed and merged to server xml. I have the pipeline visible and it executes fine. Just as it doesn't have the clean workspace option enabled, it will fail when second stage is executed on the same agent as the first one as there are some leftovers. There are no errors

**Comment by tomzo** [comment]
Closing due to lack of more info.
I see no issues with `clean_workspace` in any of my repositories.

**Comment by matthiaskraaz** [comment]
I also ran into this issue.

My YAML:

```
format_version: 9
pipelines:
  Test:
    group: Test
    materials:
      svn:
        svn: svn://lsdata/osis/trunk
    stages:
    - Clean:
        fetch_materials: "no"
        cleanWorkingDir: "yes"
        tasks: []
```

GUI shows after config repo update:

![image](https://user-images.githubusercontent.com/5954500/192350496-c9712189-1fb6-43bd-85e3-06729cba7cb8.png)

Go Server: 21.1.0

**Comment by tomzo** [comment]
Hi @matthiaskraaz clean_workspace is the keyword, your config has cleanWorkingDir

**Comment by matthiaskraaz** [comment]
Thank you, now it works.
