### ISSUE TITLE
Job fails for config pipeline with an empty environment variable 

### ISSUE THREAD

**Issue by adityasood** [tomzo/gocd-yaml-config-plugin#73]
**Issue Type**
Bug Report

**Summary**
Pipeline job fails if there is no value for environment variable in a config pipeline. Environment variable with empty value doesn't show up in console log. Nothing relevant in the go-server and go-agent log.

[go] Start to prepare yamlpipe1/5/build/1/build on 1d97d5e007cf [/var/lib/go-agent]
[go] Start to build yamlpipe1/5/build/1/build on 1d97d5e007cf [/var/lib/go-agent]
[go] Task: /bin/bash -c ls took: 0.1s
[go] Task status: failed, took: 0.1s
[go] Current job status: failed

**Basic environment details**
Go Version: 18.3
Plugin Version:0.6.2
Steps to Reproduce
Create yaml or json pipeline config repo
Add pipeline environment variable with empty value
**For example below:**

environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - yaml-example
pipelines:
  yamlpipe1:
    group: simple
    materials:
      mygit: 
        git: /repos/main_repo
    environment_variables:
        EMPTY_ENV:    #(environment variable with empty value)
    stages:
      - build: 
          jobs:
            build: 
              tasks:
               - exec: 
                   command: /bin/bash
                   arguments:
                   - -c
                   - ls
**Expected Results**
Pipeline should run without any issue as it works in older GoCD versions( till 18.2.0 with plugin v0.6.0)

**Possible Fix**
Add "" to the environment variable value instead of leaving it empty.

EMPTY_ENV: ""

**Comment by adityasood** [comment]
#https://github.com/gocd/gocd/issues/4673

**Comment by adityasood** [comment]
Reference to an issue on GoCD #gocd/gocd#4673

**Comment by tomzo** [comment]
fixed in gocd https://github.com/gocd/gocd/issues/4673
