### ISSUE TITLE
Question: auto build feature branch

### ISSUE THREAD

**Issue by Hkyx** [tomzo/gocd-yaml-config-plugin#78]
Hi, 

Is it possible from the yaml plugin to trigger (and how), a build from each feature branch linked to another ?
Example: 
I got: myBranch who get below myBranch2, 3 .... 
When I commit on the 2 or 3th branch, I want to start de build.

Thank,

Hk

**Comment by thatsk** [comment]
is there any progress on this
?

**Comment by tomzo** [comment]
For the record, some more discussion about [this](https://gitter.im/gocd/configrepo-plugins?at=5cac4fa2bd70a40d5f1ddc0) and related gocd proposal https://github.com/gocd/gocd/issues/6123
